### ISSUE TITLE
I'm a newbe.  Problem with TV shows working

### ISSUE THREAD

**Issue by roclinemedia** [crazydevman/mute-profanity#30]
I have been able to get movies to work just fine through the mute profanity add-on.  My issue is that when I go to edit TV shows it says it can't find a subtitle file and then when I click to download one it gives an error. (log below)

I essentially have a "TV Shows" Folder with individual subfolders for each show.  I also have a subfolder of each season with in each show.  I then have the mkv/mp4 file named VEEP - so1eo1 and a srt file named VEEP - so1e01.

I am wondering if I have it structured wrong or if the issue is something else altogether.  Thank you so much for your great work on this add-on!

I am a total beginner at kodi/basic programming so I am posting a decent chunk of the log that will show what is happening.  Thanks in advance!
Log:

12:20:53 T:3824  NOTICE: episodeId: 20
12:20:53 T:3824  NOTICE: response from query {"jsonrpc": "2.0", "method": "VideoLibrary.GetEpisodeDetails", "params": {"episodeid": 20, "properties" : ["showtitle", "file"]}, "id": 1}
                                            {"id":1,"jsonrpc":"2.0","result":{"episodedetails":{"episodeid":20,"file":"I:\\TV Shows\\Veep\\Veep - s01e01 - Fundraiser.mkv","label":"Fundraiser","showtitle":"Veep"}}}
12:20:53 T:3824  NOTICE: details: {'showtitle': 'Veep', 'episodeid': 20, 'file': 'I:\\TV Shows\\Veep\\Veep - s01e01 - Fundraiser.mkv', 'label': 'Fundraiser'}
12:20:55 T:3824  NOTICE: head: Veep - s01e01 - Fundraiser
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x02 - Frozen Yoghurt.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x02 - Frozen Yoghurt.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x03 - Catherine.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x03 - Catherine.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x04 - Chung.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x04 - Chung.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x05 - Nicknames.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x05 - Nicknames.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x06 - Baseball.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x06 - Baseball.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x07 - Full Disclosure.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x07 - Full Disclosure.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x08 - Tears.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - 1x08 - Tears.srt
12:20:55 T:3824  NOTICE: Checking fname: Veep - s01e01 - Fundraiser.mkv
12:20:55 T:3824  NOTICE: Checking fname: Veep - s01e01 - Fundraiser.srt
12:20:55 T:3824  NOTICE: Found existing SRT file: I:\TV Shows\Veep\Veep - s01e01 - Fundraiser.srt
12:20:55 T:3824  NOTICE: Using srt file: I:\TV Shows\Veep\Veep - s01e01 - Fundraiser.srt
12:20:55 T:3824   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: createEDL() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\media center\AppData\Roaming\Kodi\addons\mute-profanity-master\addon.py", line 39, in <module>
                                                nav.handle(params)
                                              File "C:\Users\media center\AppData\Roaming\Kodi\addons\mute-profanity-master\resources\lib\nav.py", line 191, in handle
                                                if createEDL(srtLoc):
                                            TypeError: createEDL() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--
12:20:55 T:6220   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mute-profanity/?id=20&mode=mute-episode
12:20:55 T:6220   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mute-profanity/?id=20&mode=mute-episode) failed
12:20:55 T:1792  NOTICE: response from query {"jsonrpc": "2.0", "method": "VideoLibrary.GetEpisodes", "params": {"properties": ["showtitle", "thumbnail", "file"], "sort": {"method": "episode"}, "tvshowid":2}, "id": 1}
                                            {"id":1,"jsonrpc":"2.0","result":{"episodes":[{"episodeid":20,"file":"I:\\TV Shows\\Veep\\Veep - s01e01 - Fundraiser.mkv","label":"1x01. Fundraiser","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4234716.jpg/"},{"episodeid":13,"file":"I:\\TV Shows\\Veep\\Veep - 1x02 - Frozen Yoghurt.mkv","label":"1x02. Frozen Yoghurt","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303020.jpg/"},{"episodeid":14,"file":"I:\\TV Shows\\Veep\\Veep - 1x03 - Catherine.mkv","label":"1x03. Catherine","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303021.jpg/"},{"episodeid":15,"file":"I:\\TV Shows\\Veep\\Veep - 1x04 - Chung.mkv","label":"1x04. Chung","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303022.jpg/"},{"episodeid":16,"file":"I:\\TV Shows\\Veep\\Veep - 1x05 - Nicknames.mkv","label":"1x05. Nicknames","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303023.jpg/"},{"episodeid":17,"file":"I:\\TV Shows\\Veep\\Veep - 1x06 - Baseball.mkv","label":"1x06. Baseball","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303024.jpg/"},{"episodeid":18,"file":"I:\\TV Shows\\Veep\\Veep - 1x07 - Full Disclosure.mkv","label":"1x07. Full Disclosure","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4314592.jpg/"},{"episodeid":19,"file":"I:\\TV Shows\\Veep\\Veep - 1x08 - Tears.mkv","label":"1x08. Tears","showtitle":"Veep","thumbnail":"image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4314593.jpg/"}],"limits":{"end":8,"start":0,"total":8}}}
12:20:55 T:1792  NOTICE: episodes: [{'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4234716.jpg/', 'showtitle': 'Veep', 'episodeid': 20, 'file': 'I:\\TV Shows\\Veep\\Veep - s01e01 - Fundraiser.mkv', 'label': '1x01. Fundraiser'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303020.jpg/', 'showtitle': 'Veep', 'episodeid': 13, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x02 - Frozen Yoghurt.mkv', 'label': '1x02. Frozen Yoghurt'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303021.jpg/', 'showtitle': 'Veep', 'episodeid': 14, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x03 - Catherine.mkv', 'label': '1x03. Catherine'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303022.jpg/', 'showtitle': 'Veep', 'episodeid': 15, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x04 - Chung.mkv', 'label': '1x04. Chung'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303023.jpg/', 'showtitle': 'Veep', 'episodeid': 16, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x05 - Nicknames.mkv', 'label': '1x05. Nicknames'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4303024.jpg/', 'showtitle': 'Veep', 'episodeid': 17, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x06 - Baseball.mkv', 'label': '1x06. Baseball'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4314592.jpg/', 'showtitle': 'Veep', 'episodeid': 18, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x07 - Full Disclosure.mkv', 'label': '1x07. Full Disclosure'}, {'thumbnail': 'image://http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f237831%2f4314593.jpg/', 'showtitle': 'Veep', 'episodeid': 19, 'file': 'I:\\TV Shows\\Veep\\Veep - 1x08 - Tears.mkv', 'label': '1x08. Tears'}]

**Comment by roclinemedia** [comment]
Looks like problem was already solved in a frequent thread.  Thank you -  works great!
