### ISSUE TITLE
Support smb file paths

### ISSUE THREAD

**Issue by crazydevman** [crazydevman/mute-profanity#8]
User mathmansteve tested the plugin where the media files are on samba shares. Here's his posted log:

23:32:12 T:2608 NOTICE: -->Python Interpreter Initialized<--
23:32:12 T:2608 NOTICE: movieid: 364
23:32:12 T:2608 NOTICE: movie details call response: {"id":1,"jsonrpc":"2.0","result":{"moviedetails":{"file":"smb://HTPC/Movies/Knight and Day/Knight and Day (2010).mkv","label":"Knight and Day","movieid":364,"title":"Knight and Day"}}}
23:32:12 T:2608 NOTICE: details: {'title': 'Knight and Day', 'movieid': 364, 'file': 'smb://HTPC/Movies/Knight and Day/Knight and Day (2010).mkv', 'label': 'Knight and Day'}
23:32:14 T:2608 NOTICE: head: smb://HTPC/Movies/Knight and Day/Knight and Day (2010)
23:32:14 T:2608 NOTICE: No srt file!
23:32:16 T:2608 NOTICE: Downloading
23:32:16 T:2608 NOTICE: Contacting http://www.opensubtitles.org (smb://HTPC/Movies/Knight and Day/Knight and Day (2010).mkv)
23:32:16 T:2608 NOTICE: Traceback (most recent call last):
File "C:\Users\StephenM\AppData\Roaming\XBMC\addons\plugin.video.mute-profanity\addon.py", line 126, in <module>
dl.FindSubtitles(fileLoc,"eng")
File "C:\Users\StephenM\AppData\Roaming\XBMC\addons\plugin.video.mute-profanity\resources\lib\SubDownloader.py", line 22, in FindSubtitles
data = GetSubtitles(videoname);
File "C:\Users\StephenM\AppData\Roaming\XBMC\addons\plugin.video.mute-profanity\resources\lib\SubDownloader.py", line 42, in GetSubtitles
moviebytesize = os.path.getsize(moviepath)
File "C:\Program Files (x86)\XBMC\system\python\Lib\genericpath.py", line 49, in getsize
return os.stat(filename).st_size
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb://HTPC/Movies/Knight and Day/Knight and Day (2010).mkv'

I might try to dig into the code when I get some time to help but python is not my strong suit so I might not be of much help. Let me know if you want me to try something. 

Thanks for this good start!

Stephen

I think one of the xbmc python modules can translate the path to something python can use, but I'm not sure.

**Comment by hotterpop** [comment]
I am having a similar issue with an NFS mount. I'm running Android 4.2 on a FireTV, Kodi version 15.1.

Here is the relevant debug:
22:03:26 T:1074711576   DEBUG: ------ Window Deinit (DialogYesNo.xml) ------
22:03:26 T:1559736816  NOTICE: head: Veep - S01E02 - Frozen Yoghurt
22:03:26 T:1559736816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (2, 'No such file or directory', 'nfs://path/to/file/TV/Veep/Season 1')
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/mute-profanity-master/addon.py", line 39, in <module>
                                                nav.handle(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/mute-profanity-master/resources/lib/nav.py", line 188, in handle
                                                srtLoc = finder.getSRT(fileLoc)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/mute-profanity-master/resources/lib/SubFinder.py", line 39, in getSRT
                                                for fname in os.listdir(os.path.dirname(fileLoc)):
                                            OSError: (2, 'No such file or directory', 'nfs://path/to/file/TV/Veep/Season 1')
                                            -->End of Python script error report<--
22:03:26 T:1074711576   DEBUG: ------ Window Init (DialogKaiToast.xml) ------

**Comment by luciuslue** [comment]
I fixed the problem on my pc. The issues was that I did not have my movies
in their own personal folder. I am unaware of how to fix this problem on
the FireTV. I have fixed the issues for KODI. Make sure that you first save
your movies in their own folder. If you have a Man of Steel movie, then
make a Man of Steel folder and keep that movie in that folder, Toy Story 3
Movie, than make a folder with that movie in their. When you run the mute
add on, it will save the subtitle and EDL for  that movie in that  folder.
If you don't have your movies in their personal folder, the software will t
get confused with the collection on movies dump in one folder. This was the
issue I was having.

If you need any help please let me know.

**Comment by hotterpop** [comment]
Awesome, I'll give that a shot! Do you have any experience with tv shows?
Typically those are kept as individual files in tvShowName/season/, rather
than tvShowName/season/episodeNumber/.
I'll try grouping the tv shows in individual folders, and test it with a
movie as well. Will report back.
Thanks again!
